from app.schemas.demand_schema import ParsedReplyResponse


class ReplyParseService:
    def parse_reply(self, distributor_code: str) -> ParsedReplyResponse:
        parsed_lines = [
            self._normalize_line({
                "sku_code": "SKU001",
                "sku_name": "Mock Product 1",
                "monthly_quantity": 120,
                "raw_text": "SKU001 - Mock Product 1 - 120",
            }),
            self._normalize_line({
                "sku_code": "SKU002",
                "sku_name": "Mock Product 2",
                "monthly_quantity": 80,
                "raw_text": "SKU002 - Mock Product 2 - 80",
            }),
        ]

        return ParsedReplyResponse(
            distributor_code=distributor_code,
            confirmed_by="Mock Distributor Contact",
            notes="Placeholder parsed reply generated by ReplyParseService.",
            parsed_lines=parsed_lines,
        )

    @staticmethod
    def _normalize_line(line: dict) -> dict:
        return {
            "sku_code": line.get("sku_code", ""),
            "sku_name": line.get("sku_name"),
            "monthly_quantity": line.get("monthly_quantity"),
            "raw_text": line.get("raw_text"),
        }
